name: fitness_coach_app
description: AI-powered fitness coach app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Storage
  shared_preferences: ^2.2.3
  
  # Data Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  
  # HTTP & API
  dio: ^5.4.3+1
  
  # Database
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.21
  
  # ML
  tflite_flutter: ^0.10.4
  
  # UI Components
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  
  # Charts
  fl_chart: ^0.68.0
  
  # Utils
  intl: ^0.19.0
  collection: ^1.18.0
  path_provider: ^2.1.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/exercises.json
    - assets/images/
    - assets/icons/